const CFG=window.CRISP_CONFIG;
const RPC=CFG.supabaseUrl+'/rest/v1/rpc/';
const LS='crispday.store.session';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'NT$ '+Number(n||0).toLocaleString('zh-TW');
let token=localStorage.getItem(LS)||'',storeSlug=new URLSearchParams(location.search).get('store')||CFG.defaultStore,current='orders',timer=null,lastSig='',orders=[],lastLedger=null,store=null,deferredPrompt=null,interactionLock=false;

async function rpc(name,body={}){const r=await fetch(RPC+name,{method:'POST',headers:{apikey:CFG.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(body)});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!r.ok)throw new Error(data.message||data.error||'連線失敗');return data}
function status(msg,bad=false){$('#status').innerHTML=msg?`<div class="status${bad?' bad':''}">${esc(msg)}</div>`:''}
function twDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function fmt(v){return new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v))}
function day(v){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v))}
function setSession(t){token=t||'';if(token)localStorage.setItem(LS,token);else localStorage.removeItem(LS)}
function showGate(){clearInterval(timer);$('#loginGate').classList.remove('hidden');$('#app').classList.add('hidden')}
function showApp(){$('#loginGate').classList.add('hidden');$('#app').classList.remove('hidden')}
function applyStore(s){store=s||store;if(!store)return;$('#brandName').textContent=store.name||'脆日炸雞';$('#brandMeta').textContent=(store.address||'忠孝夜市')+' · 店家管理';$('#customerLink').href='./order.html?store='+encodeURIComponent(store.slug||storeSlug);$('#setName').value=store.name||'';$('#setBrandEn').value=store.brand_en||'';$('#setPhone').value=store.phone||'';$('#setAddress').value=store.address||'';$('#setOpen').checked=!!store.business_open;$('#setCash').checked=!!store.cash_enabled;$('#setLine').checked=!!store.linepay_enabled;$('#lineModeNote').textContent=store.linepay_live?'LINE Pay 已啟用正式付款。':'目前為測試／人工確認模式。';refreshQr()}
async function restore(){if(!token){showGate();return}try{const d=await rpc('smallshop_admin_session_info',{p_token:token});if(!d.ok)throw new Error('登入已失效');store=d.store;storeSlug=store.slug;applyStore(store);showApp();await loadOrders();startPoll()}catch(e){setSession('');showGate();status('登入已失效，請重新登入。',true)}}

$('#loginBtn').onclick=async()=>{const slug=$('#storeSlug').value.trim(),pass=$('#passcode').value.trim();if(!slug||!pass){status('請輸入店家代碼與管理密碼。',true);return}$('#loginBtn').disabled=true;try{const d=await rpc('smallshop_admin_login',{p_store_slug:slug,p_passcode:pass});if(!d.ok){status(d.error||'登入失敗',true);return}storeSlug=slug;setSession(d.token);store=d.store;status('');showApp();const info=await rpc('smallshop_admin_session_info',{p_token:token});store=info.store;applyStore(store);await loadOrders();startPoll()}catch(e){status(e.message||'登入失敗',true)}finally{$('#loginBtn').disabled=false}}
$('#passcode').addEventListener('keydown',e=>{if(e.key==='Enter')$('#loginBtn').click()});
$('#showSetupBtn').onclick=()=>$('#setupBox').classList.toggle('hidden');
$('#setupBtn').onclick=async()=>{const slug=$('#storeSlug').value.trim(),setup=$('#setupToken').value.trim(),next=$('#newPasscode').value.trim();if(!slug||!setup||!next){status('請填寫店家代碼、首次設定碼與新密碼。',true);return}$('#setupBtn').disabled=true;try{const d=await rpc('smallshop_admin_setup',{p_store_slug:slug,p_setup_token:setup,p_new_passcode:next});if(!d.ok){status(d.error||'首次設定失敗',true);return}storeSlug=slug;setSession(d.token);const info=await rpc('smallshop_admin_session_info',{p_token:token});store=info.store;applyStore(store);showApp();status('首次設定完成。');await loadOrders();startPoll()}catch(e){status(e.message||'首次設定失敗',true)}finally{$('#setupBtn').disabled=false}}

$$('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
function switchTab(name){current=name;$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.pane').forEach(p=>p.classList.add('hidden'));$('#pane-'+name).classList.remove('hidden');status('');if(name==='ledger')loadLedger();if(name==='menu')loadMenuAdmin();if(name==='settings')loadStore();if(name==='qr')refreshQr()}
function startPoll(){clearInterval(timer);timer=setInterval(()=>{if(current==='orders'&&!document.hidden&&!interactionLock)loadOrders(true)},5000)}
function orderSignature(a){return JSON.stringify(a.map(o=>[o.id,o.updated_at,o.status,o.payment_status,o.total]))}
function orderMetrics(a){const live=a.filter(o=>o.status!=='已取消');return{revenue:live.filter(o=>o.payment_status==='已收款').reduce((s,o)=>s+Number(o.total||0),0),count:live.length,unpaid:live.filter(o=>o.payment_status!=='已收款').length,making:live.filter(o=>o.status==='製作中').length}}
function metric(label,val){return `<section class="panel metric-card"><div class="metric-label">${esc(label)}</div><div class="metric-value">${esc(val)}</div></section>`}
async function loadOrders(silent=false){try{const d=await rpc('smallshop_admin_orders',{p_token:token});orders=Array.isArray(d.orders)?d.orders:[];const m=orderMetrics(orders);$('#orderMetrics').innerHTML=metric('今日營業額',money(m.revenue))+metric('今日訂單',m.count)+metric('未收款',m.unpaid)+metric('製作中',m.making);const sig=orderSignature(orders);if(sig===lastSig)return;lastSig=sig;renderOrders();if(!silent)status('')}catch(e){if(/登入/.test(e.message)){setSession('');showGate()}status(e.message||'訂單讀取失敗',true)}}
function renderOrders(){if(!orders.length){$('#orders').innerHTML='<section class="panel">目前沒有訂單</section>';return}$('#orders').innerHTML=orders.map(o=>`<article class="order-card"><div class="order-top"><div><span class="order-no">${esc(o.order_no)}</span> <span class="pill">${esc(o.status)}</span></div><div class="order-price">${money(o.total)}</div></div><div class="order-items">${(o.items||[]).map(i=>esc(i.name)+' ×'+Number(i.qty||0)).join('、')}</div><div class="order-meta">${esc(o.dining_type)}${o.table_no?' · 桌 '+esc(o.table_no):''} · ${esc(o.payment_method)} · ${esc(o.payment_status)} · ${fmt(o.created_at)}</div>${o.note?`<div class="order-note">備註：${esc(o.note)}</div>`:''}<div class="order-actions">${o.payment_status!=='已收款'?`<button class="btn btn-soft act" data-id="${o.id}" data-action="paid">確認收款</button>`:''}${o.status==='新訂單'?`<button class="btn btn-yellow act" data-id="${o.id}" data-action="making">開始製作</button>`:''}${o.status==='製作中'?`<button class="btn btn-dark act" data-id="${o.id}" data-action="done">完成</button>`:''}<button class="btn btn-ghost print" data-id="${o.id}">列印</button>${!['已完成','已取消'].includes(o.status)?`<button class="btn btn-danger act" data-id="${o.id}" data-action="cancel">取消</button>`:''}</div></article>`).join('')}
$('#orders').addEventListener('pointerdown',()=>{interactionLock=true;setTimeout(()=>interactionLock=false,1400)});
$('#orders').addEventListener('click',async e=>{const pb=e.target.closest('.print');if(pb){const o=orders.find(x=>Number(x.id)===Number(pb.dataset.id));if(o)printReceipt(o);return}const b=e.target.closest('.act');if(!b)return;interactionLock=true;b.disabled=true;try{await rpc('smallshop_admin_update',{p_token:token,p_id:Number(b.dataset.id),p_action:b.dataset.action});lastSig='';await loadOrders()}catch(err){status(err.message||'更新失敗',true)}finally{interactionLock=false;b.disabled=false}});
$('#refreshOrders').onclick=()=>loadOrders();
function printReceipt(o){const rows=(o.items||[]).map(i=>`<div style="display:flex;justify-content:space-between;margin:5px 0"><span>${esc(i.name)} ×${i.qty}</span><span>${money(Number(i.price||0)*Number(i.qty||0))}</span></div>`).join('');const w=open('','_blank');if(!w)return;w.document.write(`<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><body style="font-family:sans-serif;width:72mm;margin:auto;padding:5mm"><div style="text-align:center;font-size:24px;font-weight:900">${esc(store?.name||'脆日炸雞')}</div><div style="text-align:center;font-size:11px">${esc(store?.address||'忠孝夜市')}</div><div style="text-align:center;font-size:30px;font-weight:900;margin:8px">${esc(o.order_no)}</div><hr>${rows}<hr><b>合計 ${money(o.total)}</b><p>${esc(o.dining_type)}${o.table_no?' · 桌 '+esc(o.table_no):''}<br>${esc(o.payment_method)} · ${esc(o.payment_status)}<br>${fmt(o.created_at)}</p><button onclick="print()" style="width:100%;padding:12px">列印訂單</button></body></html>`);w.document.close()}

function setToday(){const d=twDate();$('#fromDate').value=d;$('#toDate').value=d}function setMonth(){const d=twDate();$('#fromDate').value=d.slice(0,8)+'01';$('#toDate').value=d}
function summarize(a){const valid=a.filter(o=>o.status!=='已取消'),paid=valid.filter(o=>o.payment_status==='已收款'),daily={},products={};for(const o of valid){const k=day(o.created_at);daily[k]??={date:k,orders:0,revenue:0,cash:0,line:0,unpaid:0};daily[k].orders++;if(o.payment_status==='已收款'){daily[k].revenue+=Number(o.total||0);if(o.payment_method==='LINE Pay')daily[k].line+=Number(o.total||0);else daily[k].cash+=Number(o.total||0)}else daily[k].unpaid++;for(const i of o.items||[]){products[i.name]??={name:i.name,qty:0,amount:0};products[i.name].qty+=Number(i.qty||0);products[i.name].amount+=Number(i.price||0)*Number(i.qty||0)}}const revenue=paid.reduce((s,o)=>s+Number(o.total||0),0),cash=paid.filter(o=>o.payment_method==='現金').reduce((s,o)=>s+Number(o.total||0),0),line=paid.filter(o=>o.payment_method==='LINE Pay').reduce((s,o)=>s+Number(o.total||0),0);return{m:{revenue,cash,line,count:valid.length,unpaid:valid.filter(o=>o.payment_status!=='已收款').length,avg:valid.length?Math.round(revenue/valid.length):0},daily:Object.values(daily).sort((a,b)=>b.date.localeCompare(a.date)),products:Object.values(products).sort((a,b)=>b.qty-a.qty)}}
async function loadLedger(){const from=$('#fromDate').value,to=$('#toDate').value;if(!from||!to)return;$('#queryLedger').disabled=true;try{const d=await rpc('smallshop_ledger',{p_token:token,p_from:from,p_to:to}),a=Array.isArray(d.orders)?d.orders:[],s=summarize(a);lastLedger={from:d.from||from,to:d.to||to,orders:a};$('#ledgerMetrics').innerHTML=metric('營業額',money(s.m.revenue))+metric('訂單',s.m.count)+metric('現金',money(s.m.cash))+metric('LINE Pay',money(s.m.line));$('#dailyRows').innerHTML=s.daily.length?s.daily.map(x=>`<tr><td>${x.date}</td><td>${x.orders}</td><td>${money(x.revenue)}</td><td>${money(x.cash)}</td><td>${money(x.line)}</td><td>${x.unpaid}</td></tr>`).join(''):'<tr><td colspan="6">沒有資料</td></tr>';$('#productRanks').innerHTML=s.products.length?s.products.map((x,i)=>`<div class="rank-row"><b>${i+1}. ${esc(x.name)}</b><span>${x.qty} 份</span><b>${money(x.amount)}</b></div>`).join(''):'沒有商品銷售資料';$('#ledgerRows').innerHTML=a.length?a.map(o=>`<tr><td>${fmt(o.created_at)}</td><td><b>${esc(o.order_no)}</b></td><td>${esc((o.items||[]).map(i=>i.name+'×'+i.qty).join('、'))}</td><td>${money(o.total)}</td><td>${esc(o.payment_method)}</td><td>${esc(o.payment_status)}</td><td>${esc(o.status)}</td></tr>`).join(''):'<tr><td colspan="7">沒有訂單</td></tr>'}catch(e){status(e.message||'帳目讀取失敗',true)}finally{$('#queryLedger').disabled=false}}
$('#todayBtn').onclick=()=>{setToday();loadLedger()};$('#monthBtn').onclick=()=>{setMonth();loadLedger()};$('#queryLedger').onclick=loadLedger;setToday();
$('#exportCsv').onclick=()=>{if(!lastLedger){status('請先查詢帳目。',true);return}const q=v=>'"'+String(v??'').replace(/"/g,'""').replace(/\r?\n/g,' ')+'"',rows=[['時間','訂單','餐點','金額','付款方式','收款狀態','訂單狀態']];for(const o of lastLedger.orders)rows.push([fmt(o.created_at),o.order_no,(o.items||[]).map(i=>i.name+' x'+i.qty).join('、'),Number(o.total||0),o.payment_method,o.payment_status,o.status]);const blob=new Blob(['\ufeff'+rows.map(r=>r.map(q).join(',')).join('\r\n')+'\r\n'],{type:'text/csv;charset=utf-8'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=`${store?.name||'店家'}_營業流水_${lastLedger.from}_${lastLedger.to}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};

let menuData=[];async function loadMenuAdmin(){try{const d=await rpc('smallshop_admin_menu',{p_token:token});menuData=Array.isArray(d.menu)?d.menu:[];renderMenuAdmin()}catch(e){status(e.message||'菜單讀取失敗',true)}}
function renderMenuAdmin(){const cats=[...new Set(menuData.map(x=>x.category))];$('#categoryList').innerHTML=cats.map(c=>`<option value="${esc(c)}"></option>`).join('');$('#menuSummary').textContent=`共 ${menuData.length} 項 · ${cats.length} 個分類 · 上架 ${menuData.filter(x=>x.active).length} 項`;$('#menuAdmin').innerHTML=menuData.map(x=>`<div class="menu-row${x.active?'':' off'}"><div><div class="menu-name">${esc(x.name)}</div><div class="menu-cat">${esc(x.category)}</div></div><div class="desktop-only">${money(x.price)}</div><div class="desktop-only">排序 ${Number(x.sort_order||0)}</div><div class="menu-status">${x.active?'販售中':'已停售'}</div><button class="btn btn-ghost edit-menu" data-id="${x.id}">編輯</button></div>`).join('')}
function openMenuEditor(item){$('#menuEditor').classList.remove('hidden');$('#menuEditorTitle').textContent=item?'編輯商品':'新增商品';$('#menuId').value=item?.id||'';$('#menuName').value=item?.name||'';$('#menuPrice').value=item?.price??'';$('#menuCategory').value=item?.category||'';$('#menuSort').value=item?.sort_order??menuData.length+1;$('#menuActive').checked=item?!!item.active:true;$('#menuName').focus()}
$('#newMenuBtn').onclick=()=>openMenuEditor(null);$('#cancelMenuBtn').onclick=()=>$('#menuEditor').classList.add('hidden');$('#menuAdmin').addEventListener('click',e=>{const b=e.target.closest('.edit-menu');if(!b)return;openMenuEditor(menuData.find(x=>Number(x.id)===Number(b.dataset.id)))});
$('#saveMenuBtn').onclick=async()=>{const body={p_token:token,p_id:$('#menuId').value?Number($('#menuId').value):null,p_name:$('#menuName').value.trim(),p_price:Number($('#menuPrice').value),p_category:$('#menuCategory').value.trim(),p_active:$('#menuActive').checked,p_sort_order:Number($('#menuSort').value||0)};$('#saveMenuBtn').disabled=true;try{await rpc('smallshop_admin_menu_save',body);$('#menuEditor').classList.add('hidden');status('商品已儲存。');await loadMenuAdmin()}catch(e){status(e.message||'商品儲存失敗',true)}finally{$('#saveMenuBtn').disabled=false}};

async function loadStore(){try{const d=await rpc('smallshop_admin_session_info',{p_token:token});store=d.store;applyStore(store)}catch(e){status(e.message||'店家資料讀取失敗',true)}}
$('#saveStoreBtn').onclick=async()=>{$('#saveStoreBtn').disabled=true;try{const d=await rpc('smallshop_admin_store_save',{p_token:token,p_name:$('#setName').value,p_brand_en:$('#setBrandEn').value,p_phone:$('#setPhone').value,p_address:$('#setAddress').value,p_business_open:$('#setOpen').checked,p_cash_enabled:$('#setCash').checked,p_linepay_enabled:$('#setLine').checked});store=d.store;applyStore(store);status('店家設定已儲存。')}catch(e){status(e.message||'店家設定儲存失敗',true)}finally{$('#saveStoreBtn').disabled=false}};
$('#changePassBtn').onclick=async()=>{const cur=$('#currentPass').value.trim(),next=$('#changePass').value.trim();if(!cur||!next){status('請輸入目前密碼與新密碼。',true);return}try{const d=await rpc('smallshop_admin_change_passcode',{p_token:token,p_current:cur,p_new:next});if(!d.ok){status(d.error||'密碼更新失敗',true);return}$('#currentPass').value='';$('#changePass').value='';status('管理密碼已更新。')}catch(e){status(e.message||'密碼更新失敗',true)}};
$('#logoutBtn').onclick=async()=>{try{await rpc('smallshop_admin_logout',{p_token:token})}catch{}setSession('');store=null;showGate();status('已登出此裝置。')};
function refreshQr(){const u=new URL('./order.html',location.href);u.searchParams.set('store',store?.slug||storeSlug);$('#qrUrl').textContent=u.href;$('#openQrUrl').href=u.href}
$('#copyQrUrl').onclick=async()=>{try{await navigator.clipboard.writeText($('#qrUrl').textContent);status('點餐網址已複製。')}catch{status('無法自動複製，請長按網址複製。',true)}};

const standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;if(!standalone)$('#installBtn').classList.remove('hidden');addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;return}const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);$('#installHint').classList.remove('hidden');$('#installHint').textContent=ios?'iPhone / iPad：請用 Safari 開啟，點「分享」→「加入主畫面」。':'請開啟瀏覽器選單，選擇「安裝應用程式」或「加入主畫面」。'};addEventListener('appinstalled',()=>{$('#installBtn').classList.add('hidden');status('店家 App 已安裝。')});
restore();
